### ISSUE TITLE
Refresh tokens

### ISSUE THREAD

**Issue by Adam-Cierniak** [czworcaInformatyczna/wsb2022-rb6-backend#3]
pls add

**Comment by CichockiMateusz** [comment]
Refresh tokens would required to use a thrid party server or having separate authentication server, neither of this solutions are in plans so for now our auth system won't use refresh tokens

**Comment by CichockiMateusz** [comment]
Refresh tokens would required to use a thrid party server or having separate authentication server, neither of this solutions are in plans so for now our auth system won't use refresh tokens

**Comment by CichockiMateusz** [comment]
Refresh tokens would required to use a thrid party server or having separate authentication server, neither of this solutions are in plans so for now our auth system won't use refresh tokens
